name: testekobe
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #Internal
  provider: ^6.1.5+1
  signals: ^6.2.0
  dio: ^5.9.0
  go_router: ^17.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  freezed_annotation: ^3.1.0



  #UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3

flutter:

  uses-material-design: true